substitutions:
  _REGION: europe-west9
  _REPOSITORY: cloud-run-source-deploy
  _SERVICE: dalaransiege-api
  _RUNTIME_SERVICE_ACCOUNT: dalaransiege-api@dalaransiege.iam.gserviceaccount.com

steps:
  - id: build-backend
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --tag
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:$BUILD_ID
      - backend

  - id: push-backend
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:$BUILD_ID

  - id: deploy-backend
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:$BUILD_ID
      - --project=$PROJECT_ID
      - --region=${_REGION}
      - --service-account=${_RUNTIME_SERVICE_ACCOUNT}
      - --min-instances=0
      - --max-instances=1
      - --cpu=1
      - --memory=512Mi
      - --concurrency=20
      - --timeout=30s
      - --set-secrets=SUPABASE_DB_PASSWORD=supabase-db-password:latest
      - --quiet

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:$BUILD_ID

options:
  logging: CLOUD_LOGGING_ONLY
